-- MySQL Script generated by MySQL Workbench
-- Tue Jan 29 20:39:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AffiliationRecordsTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AffiliationRecordsTable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AffiliationRecordsTable` (
  `clubID` VARCHAR(50) NOT NULL,
  `dateUpdated` DATE NOT NULL,
  `region` VARCHAR(10) NULL,
  `level` TINYINT(1) NULL,
  `type` TINYINT(1) NULL,
  `school` VARCHAR(100) NULL,
  `clubName` VARCHAR(100) NULL,
  `address` VARCHAR(200) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `adviserName` VARCHAR(100) NULL,
  `contact` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`clubID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AffiliationTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AffiliationTable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AffiliationTable` (
  `affiliationID` SMALLINT(10) NOT NULL,
  `affiliated` TINYINT(1) NOT NULL,
  `status` VARCHAR(45) NULL,
  `hasAffiliationForms` TINYINT(1) NULL,
  `benefits` VARCHAR(200) NULL,
  `remarks` VARCHAR(200) NULL,
  `schoolYear` YEAR(4) NULL,
  `yearsAffiliated` INT NULL,
  `SCA` SMALLINT(10) NULL,
  `SCM` SMALLINT(10) NULL,
  `paymentMode` VARCHAR(200) NULL,
  `paymentDate` DATE NULL,
  `paymentID` VARCHAR(200) NULL,
  `paymentAmount` INT NULL,
  `receiptNumber` VARCHAR(200) NULL,
  `paymentSendMode` VARCHAR(200) NULL,
  `AffiliationRecordsTable_clubID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`affiliationID`, `AffiliationRecordsTable_clubID`),
  INDEX `fk_AffiliationTable_AffiliationRecordsTable_idx` (`AffiliationRecordsTable_clubID` ASC),
  CONSTRAINT `fk_AffiliationTable_AffiliationRecordsTable`
    FOREIGN KEY (`AffiliationRecordsTable_clubID`)
    REFERENCES `mydb`.`AffiliationRecordsTable` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
